### ISSUE TITLE
no valid OpenPGP data found for repo ppa:nathan-renniewaldock/flux

### ISSUE THREAD

**Issue by KarelWintersky** [xflux-gui/fluxgui#116]
```
root@rubytower:~# add-apt-repository ppa:nathan-renniewaldock/flux
 GUI for f.lux
https://justgetflux.com/

Bugs/feature requests should be directed to: https://github.com/xflux-gui/xflux-gui
I do not develop this, only provide a PPA.
 More info: https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmptyskr4im/pubring.gpg' created
gpg: /tmp/tmptyskr4im/trustdb.gpg: trustdb created
gpg: key 4CDB129629A4B41A: public key "Launchpad PPA for Nathan Rennie-Waldock" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'S.gpg-agent.browser'

```

**Comment by ntc2** [comment]
Hi @KarelWintersky. This looks a problem with the PPA or with your GPG setup. We don't maintain the PPA here. Perhaps @NHellFire, the PPA maintainer, will have something to say about this.

**Comment by NHellFire** [comment]
I'll try to remember to check this soon, I've been a bit busy lately. What Ubuntu version are you running?

**Comment by NHellFire** [comment]
Yeah, that's definitely a system issue, not an issue with the PPA. Looks like a bug in python3-software-properties
