### ISSUE TITLE
Errors when trying to launch f.lux GUI via CLI

### ISSUE THREAD

**Issue by jfalava** [xflux-gui/fluxgui#122]
Hello!
I just tried to install from source f.lux. It actually works (only when i use `./xflux12 -l 0 -g 0 -r 0 -k3400 -nofork` in the CLI) BUT when i try to launch the GUI, i get this error message:
```
(fluxgui:2817): Gtk-WARNING **: 22:40:57.793: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(fluxgui:2817): Gtk-WARNING **: 22:40:57.793: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(fluxgui:2817): Gtk-WARNING **: 22:40:57.793: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/bin/fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
  File "/usr/lib/python3.7/site-packages/fluxgui/fluxapp.py", line 8, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

I'm using Arch Linux `(Linux pc-pc 4.19.36-1-MANJARO #1 SMP PREEMPT Sat Apr 20 22:05:46 UTC 2019 x86_64 GNU/Linux)` and i have all the python dependencies it needs.
Love to get some insight. Thanks!

**Comment by rodriguez5324** [comment]
I had the same problem. Try to install `libappindicator-gtk3`

**Comment by ntc2** [comment]
Yes, sounds like a missing dependency. Thanks @rodriguez5324
