### ISSUE TITLE
fluxgui is n running anymore!

### ISSUE THREAD

**Issue by eric-jcb** [xflux-gui/fluxgui#128]
On ArchLinux   I get namespace error:
```
python3 fluxgui                                  
Traceback (most recent call last):
  File "fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
  File "/usr/lib/python3.7/site-packages/fluxgui/fluxapp.py", line 8, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

```

**Comment by revast** [comment]
Seems to be fixed by installing libappindicator-gtk3 from the AUR.
See:   https://bugs.archlinux.org/task/48838
