### ISSUE TITLE
Don't work with GTK 4

### ISSUE THREAD

**Issue by Nojipiz** [xflux-gui/fluxgui#148]
I have running this gui for a long time ago in my archlinux laptop, but after an update this dont' open again.

```
/usr/lib/python3.9/site-packages/fluxgui/fluxapp.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 137, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 257, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 109, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
  File "/usr/lib/python3.9/site-packages/fluxgui/fluxapp.py", line 4, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 139, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
```

Obviously GTK4 it is the guilty. i will try fix this

**Comment by ntc2** [comment]
Closed by #149
