### ISSUE TITLE
Issue with installing flux on manjaro

### ISSUE THREAD

**Issue by Dankra30** [xflux-gui/fluxgui#157]
Hey! I'm using manjaro xfce and am trying to install flux since I really enjoyed it when I had Windows. Now I'm a new Linux User and not that experienced in fixing problems myself, so that's why it may be a problem, which can be solved easily:

When I'm trying to do a manual installation, I've put in the command from the README: "sudo ./setup.py install --record installed.txt" and what comes out is the following:

Traceback (most recent call last):
  File "/tmp/fluxgui/./setup.py", line 84, in <module>
    setup(name = "f.lux indicator applet",
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 474, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

I would greatly appreciate it, if it could be solved. But since I'm using manjaro it's probably not the last issue I will be having, so if a solution brought me further in the installation process, I would be glad, if you don't just close this thread, but rather let me experience flux a few days for if a new problem comes up.

Thanks alot in advance!

Kind regards,
Dankra30

**Comment by ntc2** [comment]
Hello. This is a strange looking problem: a type error deep inside importlib. I tried doing the install myself with Python 3.10.0 (I see from your stack trace that you're using some 3.10.X Python) and I didn't have any trouble.

**Comment by adiSuper94** [comment]
I am facing the same issue 😥

**Comment by MASTERdjango** [comment]
I get something similar:
~/Downloads/fluxgui-master❱✔≻ sudo ./setup.py install --record installed.txt
[sudo] password for ME: 
Traceback (most recent call last):
  File "/home/arma/Downloads/fluxgui-master/./setup.py", line 84, in <module>
    setup(name = "f.lux indicator applet",
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1040, in entry_points
    return SelectableGroups.load(eps).select(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 476, in load
    ordered = sorted(eps, key=by_group)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1037, in <genexpr>
    eps = itertools.chain.from_iterable(
                                       ^
  File "/usr/lib/python3.11/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
        ^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 954, in _normalized_name
    or super()._normalized_name
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 627, in _normalized_name
    return Prepared.normalize(self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 882, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by adiSuper94** [comment]
If you are on unix, just use redshift directly. That's what I am doing now 🤷‍♂️.

**Comment by s-ansa** [comment]
I have the same problem. I first installed flux, opened it, messed something up with configuration, and decided to reinstall. This is when the error happened. 
Ubuntu 23.10

**Comment by ntc2** [comment]
I believe this is a duplicate #178 .
