### ISSUE TITLE
Does not work Debian Bookworm 

### ISSUE THREAD

**Issue by logunovFGP** [xflux-gui/fluxgui#174]
Simply doesn't work after installations, this is the logs when I press "preview' as well as setup.py does not compiling desktop file, so I had a need to copy and compile it manually.

workpc@debian:~/Downloads/flux/fluxgui$ fluxgui

(fluxgui:544919): GLib-GIO-ERROR **: 15:06:29.902: Settings schema 'apps.fluxgui' is not installed
Trace/breakpoint trap
workpc@debian:~/Downloads/flux/fluxgui$ sudo fluxgui

(fluxgui:545329): GLib-GIO-ERROR **: 15:06:36.298: Settings schema 'apps.fluxgui' is not installed
Trace/breakpoint trap
workpc@debian:~/Downloads/flux/fluxgui$ sudo cp /usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/share/glib-2.0/schemas/apps.fluxgui.gschema.xml /usr/share/glib-2.0/schemas/
workpc@debian:~/Downloads/flux/fluxgui$ sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
workpc@debian:~/Downloads/flux/fluxgui$ fluxgui
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:3400']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:6500']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:2700']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:3400']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:6500']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:2700']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:3400']
Opening in existing browser session.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Starting backend app: ['redshift', '-x']
Starting backend app: ['xflux', '-z', '90210', '-k', '3400', '-nofork']
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 60, in _start
    self.program = pexpect.spawn(program, startup_args[1:])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 276, in _spawn
    raise ExceptionPexpect('The command was not found or was not ' +
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: xflux.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 35, in _activate_xflux
    self.xflux_controller.start()
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/settings/xflux.py", line 21, in start
    super().start()
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 23, in start
    self.state.start(startup_args)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 35, in start
    self.controller_ref()._start(startup_args)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 64, in _start
    raise FileNotFoundError("\nError: Please install {} in the PATH \n".format(program))
FileNotFoundError: 
Error: Please install xflux in the PATH 

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 49, in preview_click_event
    self.xflux_controller.preview_color(colsetting_temperature)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 29, in preview_color
    self.state.preview(preview_color)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 21, in preview
    raise MethodUnavailableError(
fluxgui.exceptions.MethodUnavailableError: Xflux cannot preview in its current state
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:3400']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:6500']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:3400']
Starting backend app: ['redshift', '-x']
Starting backend app: ['redshift', '-o', '-l', ':', '-t', '6500:3400']
Starting backend app: ['redshift', '-x']
Starting backend app: ['xflux', '-z', '90210', '-k', '3400', '-nofork']
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 60, in _start
    self.program = pexpect.spawn(program, startup_args[1:])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 276, in _spawn
    raise ExceptionPexpect('The command was not found or was not ' +
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: xflux.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 35, in _activate_xflux
    self.xflux_controller.start()
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/settings/xflux.py", line 21, in start
    super().start()
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 23, in start
    self.state.start(startup_args)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 35, in start
    self.controller_ref()._start(startup_args)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 64, in _start
    raise FileNotFoundError("\nError: Please install {} in the PATH \n".format(program))
FileNotFoundError: 
Error: Please install xflux in the PATH 

Starting backend app: ['xflux', '-z', '90210', '-k', '3400', '-nofork']
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 60, in _start
    self.program = pexpect.spawn(program, startup_args[1:])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 276, in _spawn
    raise ExceptionPexpect('The command was not found or was not ' +
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: xflux.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/tabs/xflux.py", line 35, in _activate_xflux
    self.xflux_controller.start()
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/settings/xflux.py", line 21, in start
    super().start()
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 23, in start
    self.state.start(startup_args)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/states.py", line 35, in start
    self.controller_ref()._start(startup_args)
  File "/usr/local/lib/python3.11/dist-packages/f.lux_indicator_applet-2.0.1rc0-py3.11.egg/fluxgui/controller/__init__.py", line 64, in _start
    raise FileNotFoundError("\nError: Please install {} in the PATH \n".format(program))
FileNotFoundError: 
Error: Please install xflux in the PATH

**Comment by ntc2** [comment]
The installation is totally broken in modern Python versions, see #178.
