### ISSUE TITLE
no module named gi

### ISSUE THREAD

**Issue by aragon5956** [xflux-gui/fluxgui#175]
hello , 
i have this problem from repo : 

`(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ fluxgui 
Traceback (most recent call last):
  File "/home/alexandre/Documents/fluxgui/env/bin/fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
  File "/home/alexandre/Documents/fluxgui/env/lib/python3.12/site-packages/fluxgui/fluxapp.py", line 6, in <module>
    import fluxgui.settings as settings
  File "/home/alexandre/Documents/fluxgui/env/lib/python3.12/site-packages/fluxgui/settings/__init__.py", line 2, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi'
(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ 
`

could you help me ? 
regards

**Comment by ntc2** [comment]
Try `sudo apt install libgirepository1.0-dev`. But see also #178.
