### ISSUE TITLE
download-xflux.py does not work for me (Fedora 26)

### ISSUE THREAD

**Issue by ldorau** [xflux-gui/fluxgui#97]
```download-xflux.py``` does not work for me:

```
$ python download-xflux.py 
Downloading 64-bit xflux ...
Extracting /tmp/xflux.tgz ...
Traceback (most recent call last):
  File "download-xflux.py", line 34, in <module>
    download_xflux()
  File "download-xflux.py", line 29, in download_xflux
    tar = tarfile.open(tarchive)
  File "/usr/lib64/python2.7/tarfile.py", line 1680, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```
The downloaded file '/tmp/xflux.tgz' is in fact a html page:
```
Request Error (invalid_request)
--
Your request could not be processed. Request could not be handled
This could be caused by a misconfiguration, or possibly a malformed request.
For assistance, contact your network support team.
```
The [old version](https://raw.githubusercontent.com/xflux-gui/fluxgui/5e27b6166a205239b5d075f5568ca5edf86051cb/download-xflux.py) (before the commit https://github.com/xflux-gui/fluxgui/commit/cd0773605c8b91527c039945481856645463c064) of ```download-xflux.py``` works well.

**Comment by ntc2** [comment]
I fixed this by reverting cd07736 in 9013f8e.
